# Generated by Django 4.2.9 on 2024-03-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, default='', verbose_name='Video URL'),
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
